### ISSUE TITLE
use devDependencies

### ISSUE THREAD

**Issue by vcapretz** [pagarme/react-payment-card-component#22]
all packages on package.json are currently placed inside "dependencies", we should use "devDependencies" as well, so for production envs or builds we could save time/storage. 

I am not sure which packages can be placed in devdependencies and if it's really needed. 

my first thoughts were:
babel and lint packages, webpack-dev-server, storybook

**Comment by thiagommedeiros** [comment]
Makes sense. The project was bootstrapped with `create-reaction-app`, which places all packages in 'dependencies'. 

@derekstavis what do you think about?

**Comment by augusto-jm-amaral** [comment]
It does not make sense to be in dependencies because when they use the module all dependencies will go into the tree.

Once we are using webpack the dependencies needed to execute the project will be contained in the bundle.

I did a build of the module using the only `devDenpencies` and I had no problems adding it to another project.
